"""github-automation service.

Stage 17 GitHub automation foundation. The service runs **dry-run by
default** — every call to ``/github/...`` returns a deterministic mock
response and contacts no real GitHub API unless the request explicitly
sets ``dry_run=false`` *and* the container has a ``GITHUB_TOKEN`` env
var. The token is never logged, never echoed in responses, never
written to any artifact.

The aggregate endpoint ``POST /github/workflow/demo-pr`` walks the
issue → branch → file → PR → checks flow, writes an audit event, and
publishes a notification, so the platform has a single in-cluster
smoke for the GitHub automation pipeline.
"""

from __future__ import annotations

import contextlib
import os
import time
from datetime import datetime, timezone
from typing import Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from real_guard import evaluate_real_test_request

from shared.sdk.audit.publisher import publish_audit_event
from shared.sdk.github import GitHubClient, GitHubClientError
from shared.sdk.notifications.client import NotificationClient
from shared.sdk.secrets import default_provider
from shared.sdk.observability.metrics import (
    GITHUB_AUTOMATION_FAILURES_TOTAL,
    GITHUB_BRANCH_CREATED_TOTAL,
    GITHUB_CHECKS_READ_TOTAL,
    GITHUB_ISSUE_CREATED_TOTAL,
    GITHUB_PR_CREATED_TOTAL,
    GITHUB_REAL_TEST_ATTEMPTS_TOTAL,
    GITHUB_REAL_TEST_BLOCKED_TOTAL,
    GITHUB_REAL_TEST_DURATION_SECONDS,
    GITHUB_REAL_TEST_FAILURES_TOTAL,
    GITHUB_REAL_TEST_SUCCESS_TOTAL,
    REAL_GITHUB_GUARD_BLOCKS_TOTAL,
    REAL_GITHUB_SANDBOX_PRS_TOTAL,
    install_metrics_endpoint,
)
from shared.sdk.observability.tracing import (
    instrument_fastapi,
    instrument_httpx,
    instrument_redis,
    setup_tracing,
    start_span,
)
from shared.sdk.real_integration import evaluate_real_github_sandbox_request

DEFAULT_REPO = os.environ.get("GITHUB_DEFAULT_REPO", "coolerh250/AI-Agents-SWD")
DEFAULT_DRY_RUN = os.environ.get("GITHUB_DRY_RUN", "true").strip().lower() != "false"

setup_tracing("github-automation")
instrument_httpx()
instrument_redis()
app = FastAPI(title="github-automation")
instrument_fastapi(app, "github-automation")
install_metrics_endpoint(app)


# ---------- helpers ---------------------------------------------------------


def _dry_run_label(value: bool) -> str:
    return "true" if value else "false"


def _utcnow_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _resolve_repo(repo: str | None) -> str:
    return (repo or DEFAULT_REPO).strip()


def _resolve_dry_run(value: bool | None) -> bool:
    if value is None:
        return DEFAULT_DRY_RUN
    return bool(value)


def _client(repo: str | None, dry_run: bool | None) -> GitHubClient:
    return GitHubClient(repo=_resolve_repo(repo), dry_run=_resolve_dry_run(dry_run))


def _handle_client_error(operation: str, exc: GitHubClientError) -> HTTPException:
    GITHUB_AUTOMATION_FAILURES_TOTAL.labels(operation=operation).inc()
    status = exc.status_code or 502
    return HTTPException(
        status_code=status,
        detail={"operation": operation, "error": str(exc)},
    )


# ---------- request models --------------------------------------------------


class IssueRequest(BaseModel):
    repo: str | None = None
    title: str
    body: str = ""
    task_id: str = ""
    workflow_id: str = ""
    dry_run: bool | None = None


class BranchRequest(BaseModel):
    repo: str | None = None
    name: str
    base_branch: str = "main"
    task_id: str = ""
    workflow_id: str = ""
    dry_run: bool | None = None


class FileRequest(BaseModel):
    repo: str | None = None
    path: str
    content: str
    message: str
    branch: str
    task_id: str = ""
    workflow_id: str = ""
    dry_run: bool | None = None


class PullRequestRequest(BaseModel):
    repo: str | None = None
    title: str
    body: str
    head_branch: str
    base_branch: str = "main"
    task_id: str = ""
    workflow_id: str = ""
    dry_run: bool | None = None


class DemoPRRequest(BaseModel):
    task_id: str = "github-demo"
    workflow_id: str = ""
    repo: str | None = None
    base_branch: str = "main"
    branch_name: str = ""
    title: str = "[AI-Agents-SWD Test] github-automation demo PR"
    body_summary: str = "Automated dry-run demo PR generated by github-automation."
    file_path: str = "docs/automation-demo.md"
    file_content: str = (
        "# AI Agents SWD demo file\n\nGenerated by github-automation in dry-run mode.\n"
    )
    dry_run: bool | None = None
    risk_assessment: str = "Low — dry-run mode contacts no real GitHub API and writes no files."
    test_result: str = "Verified by tests/test_github_demo_pr_flow.py"
    rollback_plan: str = (
        "No rollback required for dry-run. For real runs: close the PR and delete the head branch."
    )


# ---------- PR body template ------------------------------------------------


def build_pr_body(req: DemoPRRequest, changed_files: list[str]) -> str:
    bullets = "\n".join(f"- `{p}`" for p in changed_files) or "- (none)"
    return (
        "## Summary\n"
        f"{req.body_summary}\n\n"
        "## Changed Files\n"
        f"{bullets}\n\n"
        "## Risk Assessment\n"
        f"{req.risk_assessment}\n\n"
        "## Test Result\n"
        f"{req.test_result}\n\n"
        "## Rollback Plan\n"
        f"{req.rollback_plan}\n"
    )


# ---------- side effects ----------------------------------------------------


async def _publish_notification(
    task_id: str, event_type: str, message: str, *, dry_run: bool
) -> None:
    """Best-effort notification publish. ``dry_run`` is recorded in the message."""
    with contextlib.suppress(Exception):
        client = NotificationClient()
        try:
            notification = client.build_notification(task_id, event_type, message)
            notification["dry_run"] = dry_run
            await client.event_bus.publish_event(NotificationClient.STREAM, notification)
        finally:
            with contextlib.suppress(Exception):
                await client.close()


async def _record_audit(
    task_id: str,
    workflow_id: str,
    summary: str,
    result: str,
    artifact_refs: dict[str, Any],
) -> None:
    """Publish a ``github_automation`` audit event onto ``stream.audit``.

    Stage 19: the unified audit path is ``stream.audit -> audit-worker ->
    audit_logs``. We no longer call ``audit-service`` over HTTP — best-effort
    suppression matches the previous behaviour.
    """
    with contextlib.suppress(Exception):
        await publish_audit_event(
            task_id=task_id,
            workflow_id=workflow_id,
            agent="github-automation",
            decision_type="github_automation",
            summary=summary,
            result=result,
            artifact_refs=artifact_refs,
        )


# ---------- routes ----------------------------------------------------------


@app.get("/health")
def health() -> dict:
    return {
        "service": "github-automation",
        "status": "ok",
        "default_repo": DEFAULT_REPO,
        "default_dry_run": DEFAULT_DRY_RUN,
        # Stage 24: token presence is read through the SecretProvider so a
        # placeholder value never reports as "present". The value itself
        # never leaves the env var.
        "has_token": default_provider().has_secret("GITHUB_TOKEN"),
        "real_github_test_enabled": (
            os.environ.get("RUN_REAL_GITHUB_TEST", "false").strip().lower() == "true"
        ),
        "test_repo_configured": bool(os.environ.get("GITHUB_TEST_REPO", "").strip()),
    }


@app.post("/github/issue")
async def create_issue(req: IssueRequest) -> dict:
    dry_run = _resolve_dry_run(req.dry_run)
    client = _client(req.repo, req.dry_run)
    try:
        issue = await client.create_issue(
            req.title,
            req.body,
            task_id=req.task_id,
            workflow_id=req.workflow_id,
        )
    except GitHubClientError as exc:
        raise _handle_client_error("create_issue", exc) from exc
    GITHUB_ISSUE_CREATED_TOTAL.labels(dry_run=_dry_run_label(dry_run)).inc()
    return {"dry_run": dry_run, "issue": issue.to_dict()}


@app.post("/github/branch")
async def create_branch(req: BranchRequest) -> dict:
    dry_run = _resolve_dry_run(req.dry_run)
    client = _client(req.repo, req.dry_run)
    try:
        branch = await client.create_branch(
            req.name,
            base_branch=req.base_branch,
            task_id=req.task_id,
            workflow_id=req.workflow_id,
        )
    except GitHubClientError as exc:
        raise _handle_client_error("create_branch", exc) from exc
    GITHUB_BRANCH_CREATED_TOTAL.labels(dry_run=_dry_run_label(dry_run)).inc()
    return {"dry_run": dry_run, "branch": branch.to_dict()}


@app.post("/github/file")
async def create_or_update_file(req: FileRequest) -> dict:
    dry_run = _resolve_dry_run(req.dry_run)
    client = _client(req.repo, req.dry_run)
    try:
        file = await client.create_or_update_file(
            req.path,
            req.content,
            req.message,
            branch=req.branch,
            task_id=req.task_id,
            workflow_id=req.workflow_id,
        )
    except GitHubClientError as exc:
        raise _handle_client_error("create_or_update_file", exc) from exc
    return {"dry_run": dry_run, "file": file.to_dict()}


@app.post("/github/pull-request")
async def create_pull_request(req: PullRequestRequest) -> dict:
    dry_run = _resolve_dry_run(req.dry_run)
    client = _client(req.repo, req.dry_run)
    try:
        pr = await client.create_pull_request(
            req.title,
            req.body,
            head_branch=req.head_branch,
            base_branch=req.base_branch,
            task_id=req.task_id,
            workflow_id=req.workflow_id,
        )
    except GitHubClientError as exc:
        raise _handle_client_error("create_pull_request", exc) from exc
    GITHUB_PR_CREATED_TOTAL.labels(dry_run=_dry_run_label(dry_run)).inc()
    return {"dry_run": dry_run, "pull_request": pr.to_dict()}


@app.get("/github/pull-request/{number}")
async def get_pull_request(number: int, repo: str | None = None, dry_run: bool = True) -> dict:
    client = _client(repo, dry_run)
    try:
        pr = await client.get_pull_request(number)
    except GitHubClientError as exc:
        raise _handle_client_error("get_pull_request", exc) from exc
    return {"dry_run": _resolve_dry_run(dry_run), "pull_request": pr.to_dict()}


@app.get("/github/checks")
async def get_checks(ref: str, repo: str | None = None, dry_run: bool = True) -> dict:
    client = _client(repo, dry_run)
    try:
        checks = await client.read_checks(ref)
    except GitHubClientError as exc:
        raise _handle_client_error("read_checks", exc) from exc
    GITHUB_CHECKS_READ_TOTAL.labels(dry_run=_dry_run_label(_resolve_dry_run(dry_run))).inc()
    return {"dry_run": _resolve_dry_run(dry_run), "checks": checks.to_dict()}


@app.post("/github/workflow/demo-pr")
async def demo_pr(req: DemoPRRequest) -> dict:
    """Walk issue → branch → file → PR → checks. Dry-run by default."""
    dry_run = _resolve_dry_run(req.dry_run)
    repo = _resolve_repo(req.repo)
    branch_name = req.branch_name or f"ai-agents-swd/demo-{req.task_id}".replace(" ", "-")

    with start_span(
        "github.demo_pr",
        **{
            "github.repo": repo,
            "github.dry_run": str(dry_run).lower(),
            "github.operation": "demo_pr",
            "task_id": req.task_id,
            "workflow_id": req.workflow_id,
        },
    ):
        client = GitHubClient(repo=repo, dry_run=dry_run)
        result: dict[str, Any] = {
            "dry_run": dry_run,
            "repo": repo,
            "task_id": req.task_id,
            "workflow_id": req.workflow_id,
            "branch_name": branch_name,
            "base_branch": req.base_branch,
            "created_at": _utcnow_iso(),
        }
        try:
            issue = await client.create_issue(
                title=f"[AI-Agents-SWD Test] {req.title}",
                body=req.body_summary,
                task_id=req.task_id,
                workflow_id=req.workflow_id,
            )
            GITHUB_ISSUE_CREATED_TOTAL.labels(dry_run=_dry_run_label(dry_run)).inc()
            result["issue"] = issue.to_dict()

            branch = await client.create_branch(
                branch_name,
                base_branch=req.base_branch,
                task_id=req.task_id,
                workflow_id=req.workflow_id,
            )
            GITHUB_BRANCH_CREATED_TOTAL.labels(dry_run=_dry_run_label(dry_run)).inc()
            result["branch"] = branch.to_dict()

            file = await client.create_or_update_file(
                req.file_path,
                req.file_content,
                message=f"[AI-Agents-SWD Test] add {req.file_path}",
                branch=branch_name,
                task_id=req.task_id,
                workflow_id=req.workflow_id,
            )
            result["file"] = file.to_dict()

            pr_body = build_pr_body(req, [req.file_path])
            pr = await client.create_pull_request(
                title=req.title,
                body=pr_body,
                head_branch=branch_name,
                base_branch=req.base_branch,
                task_id=req.task_id,
                workflow_id=req.workflow_id,
            )
            GITHUB_PR_CREATED_TOTAL.labels(dry_run=_dry_run_label(dry_run)).inc()
            result["pull_request"] = pr.to_dict()

            checks = await client.read_checks(
                branch_name,
                task_id=req.task_id,
                workflow_id=req.workflow_id,
            )
            GITHUB_CHECKS_READ_TOTAL.labels(dry_run=_dry_run_label(dry_run)).inc()
            result["checks"] = checks.to_dict()
        except GitHubClientError as exc:
            GITHUB_AUTOMATION_FAILURES_TOTAL.labels(operation="demo_pr").inc()
            raise HTTPException(
                status_code=exc.status_code or 502,
                detail={"operation": "demo_pr", "error": str(exc)},
            ) from exc

        # Side effects: notification + audit. Best-effort.
        event_type = "github.pr.dry_run" if dry_run else "github.pr.created"
        message = (
            f"github-automation demo-pr completed (dry_run={dry_run}); "
            f"issue={result['issue'].get('url', '')} "
            f"pr={result['pull_request'].get('url', '')}"
        )
        await _publish_notification(req.task_id, event_type, message, dry_run=dry_run)
        await _record_audit(
            task_id=req.task_id,
            workflow_id=req.workflow_id,
            summary=f"GitHub demo PR ({'dry-run' if dry_run else 'live'})",
            result="ok",
            artifact_refs={
                "issue_url": result["issue"].get("url", ""),
                "branch": branch_name,
                "pr_url": result["pull_request"].get("url", ""),
                "dry_run": dry_run,
            },
        )
        result["event_type"] = event_type
        return result


# ---------- Stage 23: controlled real GitHub validation ---------------------


class RealTestPRRequest(BaseModel):
    task_id: str
    workflow_id: str = ""
    repo: str
    base_branch: str = "main"
    branch_name: str
    title: str
    body: str
    file_path: str
    file_content: str
    dry_run: bool | None = None


def build_real_test_pr_body(req: RealTestPRRequest) -> str:
    """Return the caller-supplied PR body untouched, but assert the six
    required sections are present. The guard runs the same check before
    a real write — this helper only renders.
    """
    return req.body or ""


def _blocked_summary(reason: str) -> str:
    return f"real GitHub test blocked at safety guard: {reason}"


async def _record_real_test_audit(
    *,
    task_id: str,
    workflow_id: str,
    decision_type: str,
    summary: str,
    result: str,
    artifact_refs: dict[str, Any],
) -> None:
    with contextlib.suppress(Exception):
        await publish_audit_event(
            task_id=task_id,
            workflow_id=workflow_id,
            agent="github-automation",
            decision_type=decision_type,
            summary=summary,
            result=result,
            artifact_refs=artifact_refs,
        )


async def _publish_real_test_notification(
    task_id: str,
    event_type: str,
    message: str,
    *,
    pr_url: str = "",
    repo: str = "",
    branch: str = "",
    sandbox: bool = True,
) -> None:
    """Best-effort notification publish. ``sandbox=True`` even on success
    because the controlled-real flow targets a sandbox repo and explicitly
    forbids production write."""
    with contextlib.suppress(Exception):
        client = NotificationClient()
        try:
            notification = client.build_notification(task_id, event_type, message)
            notification["pr_url"] = pr_url
            notification["repo"] = repo
            notification["branch"] = branch
            notification["sandbox"] = sandbox
            notification["production_executed"] = False
            await client.event_bus.publish_event(NotificationClient.STREAM, notification)
        finally:
            with contextlib.suppress(Exception):
                await client.close()


@app.post("/github/workflow/real-test-pr")
async def real_test_pr(req: RealTestPRRequest) -> dict:
    """Controlled-real GitHub PR flow. Sandbox-by-default. Refuses with
    HTTP 409 + structured ``safety_guard_result`` unless every Stage 23
    pre-condition holds. The token is never echoed in the response.
    """
    started = time.perf_counter()
    repo_value = (req.repo or "").strip()

    with start_span(
        "github.real_test.guard",
        **{
            "github.repo": repo_value,
            "github.operation": "real_test_pr_guard",
            "task_id": req.task_id,
            "workflow_id": req.workflow_id,
            "github.dry_run": "false",
            "github.real_github_test": "true",
        },
    ):
        guard = evaluate_real_test_request(
            repo=req.repo,
            base_branch=req.base_branch,
            branch_name=req.branch_name,
            title=req.title,
            body=req.body,
            file_path=req.file_path,
            file_content=req.file_content,
            dry_run=req.dry_run,
        )

    # Stage 32 defence-in-depth: AFTER Stage 23 has passed, refuse
    # production-shaped repos + forbidden intents + forbidden file
    # paths (.github/, infra/, ...). The Stage 23 guard already
    # validates branch/title/file_path prefixes + dry_run + token +
    # opt-in + test-repo equality; the Stage 32 layer adds NEW rails
    # on top so existing Stage 23 tests still see Stage 23 reasons.
    if guard.allowed:
        with start_span(
            "real_github.guard",
            **{
                "github.repo": repo_value,
                "github.operation": "sandbox_pre_guard",
                "task_id": req.task_id,
                "workflow_id": req.workflow_id,
                "github.dry_run": "false",
                "github.real_github_test": "true",
            },
        ):
            sandbox_guard = evaluate_real_github_sandbox_request(
                repo=req.repo,
                branch_name=req.branch_name,
                title=req.title,
                file_path=req.file_path,
                intent="create_pr",
                dry_run=req.dry_run,
            )
        if not sandbox_guard.allowed:
            REAL_GITHUB_GUARD_BLOCKS_TOTAL.labels(reason=sandbox_guard.reason).inc()
            REAL_GITHUB_SANDBOX_PRS_TOTAL.labels(result="blocked").inc()
            GITHUB_REAL_TEST_BLOCKED_TOTAL.labels(
                repo=repo_value or "unknown", reason=sandbox_guard.reason
            ).inc()
            await _record_real_test_audit(
                task_id=req.task_id,
                workflow_id=req.workflow_id,
                decision_type="github_sandbox_guard_failed",
                summary=f"sandbox pre-guard refused: {sandbox_guard.reason}",
                result="blocked",
                artifact_refs={
                    "repo": repo_value,
                    "reason": sandbox_guard.reason,
                    "test_mode": True,
                    "dry_run": False,
                    "real_github_test": True,
                    "production_executed": False,
                    "details": sandbox_guard.details,
                },
            )
            raise HTTPException(
                status_code=409,
                detail={
                    "operation": "real_test_pr",
                    "safety_guard_result": sandbox_guard.to_safe_dict(),
                },
            )

    if not guard.allowed:
        GITHUB_REAL_TEST_BLOCKED_TOTAL.labels(
            repo=repo_value or "unknown", reason=guard.reason
        ).inc()
        await _record_real_test_audit(
            task_id=req.task_id,
            workflow_id=req.workflow_id,
            decision_type="github_real_test_blocked",
            summary=_blocked_summary(guard.reason),
            result="blocked",
            artifact_refs={
                "repo": repo_value,
                "reason": guard.reason,
                "dry_run": False,
                "real_github_test": True,
                "production_executed": False,
                "details": guard.details,
            },
        )
        raise HTTPException(
            status_code=409,
            detail={
                "operation": "real_test_pr",
                "safety_guard_result": guard.to_safe_dict(),
            },
        )

    GITHUB_REAL_TEST_ATTEMPTS_TOTAL.labels(repo=repo_value, result="attempted").inc()

    # The guard guarantees dry_run is exactly False at this point.
    client = GitHubClient(repo=repo_value, dry_run=False)
    result: dict[str, Any] = {
        "dry_run": False,
        "real_github_test": True,
        "production_executed": False,
        "repo": repo_value,
        "task_id": req.task_id,
        "workflow_id": req.workflow_id,
        "branch_name": req.branch_name,
        "base_branch": req.base_branch,
        "created_at": _utcnow_iso(),
        "safety_guard_result": guard.to_safe_dict(),
    }
    try:
        with start_span(
            "github.real_test.create_issue",
            **{
                "github.repo": repo_value,
                "task_id": req.task_id,
                "workflow_id": req.workflow_id,
                "github.dry_run": "false",
                "github.real_github_test": "true",
            },
        ):
            issue = await client.create_issue(
                title=req.title,
                body=req.body,
                task_id=req.task_id,
                workflow_id=req.workflow_id,
            )
            GITHUB_ISSUE_CREATED_TOTAL.labels(dry_run="false").inc()
            result["issue"] = issue.to_dict()

        with start_span(
            "github.real_test.create_branch",
            **{
                "github.repo": repo_value,
                "github.branch": req.branch_name,
                "task_id": req.task_id,
                "workflow_id": req.workflow_id,
                "github.dry_run": "false",
                "github.real_github_test": "true",
            },
        ):
            branch = await client.create_branch(
                req.branch_name,
                base_branch=req.base_branch,
                task_id=req.task_id,
                workflow_id=req.workflow_id,
            )
            GITHUB_BRANCH_CREATED_TOTAL.labels(dry_run="false").inc()
            result["branch"] = branch.to_dict()

        with start_span(
            "github.real_test.create_file",
            **{
                "github.repo": repo_value,
                "github.branch": req.branch_name,
                "github.file_path": req.file_path,
                "task_id": req.task_id,
                "workflow_id": req.workflow_id,
                "github.dry_run": "false",
                "github.real_github_test": "true",
            },
        ):
            file = await client.create_or_update_file(
                req.file_path,
                req.file_content,
                message=f"[AI-Agents-SWD Test] add {req.file_path}",
                branch=req.branch_name,
                task_id=req.task_id,
                workflow_id=req.workflow_id,
            )
            result["file"] = file.to_dict()

        with start_span(
            "github.real_test.create_pr",
            **{
                "github.repo": repo_value,
                "github.branch": req.branch_name,
                "task_id": req.task_id,
                "workflow_id": req.workflow_id,
                "github.dry_run": "false",
                "github.real_github_test": "true",
            },
        ):
            pr = await client.create_pull_request(
                title=req.title,
                body=build_real_test_pr_body(req),
                head_branch=req.branch_name,
                base_branch=req.base_branch,
                task_id=req.task_id,
                workflow_id=req.workflow_id,
            )
            GITHUB_PR_CREATED_TOTAL.labels(dry_run="false").inc()
            result["pull_request"] = pr.to_dict()

        with start_span(
            "github.real_test.read_checks",
            **{
                "github.repo": repo_value,
                "github.branch": req.branch_name,
                "task_id": req.task_id,
                "workflow_id": req.workflow_id,
                "github.dry_run": "false",
                "github.real_github_test": "true",
            },
        ):
            checks = await client.read_checks(
                req.branch_name,
                task_id=req.task_id,
                workflow_id=req.workflow_id,
            )
            GITHUB_CHECKS_READ_TOTAL.labels(dry_run="false").inc()
            result["checks"] = checks.to_dict()
    except GitHubClientError as exc:
        elapsed = time.perf_counter() - started
        GITHUB_AUTOMATION_FAILURES_TOTAL.labels(operation="real_test_pr").inc()
        GITHUB_REAL_TEST_FAILURES_TOTAL.labels(repo=repo_value, reason=exc.__class__.__name__).inc()
        GITHUB_REAL_TEST_DURATION_SECONDS.labels(repo=repo_value, result="failed").observe(elapsed)
        await _record_real_test_audit(
            task_id=req.task_id,
            workflow_id=req.workflow_id,
            decision_type="github_real_test_failed",
            summary=f"real GitHub test failed: {exc.__class__.__name__}",
            result="failed",
            artifact_refs={
                "repo": repo_value,
                "branch": req.branch_name,
                "dry_run": False,
                "real_github_test": True,
                "production_executed": False,
                "error": str(exc),
            },
        )
        raise HTTPException(
            status_code=exc.status_code or 502,
            detail={"operation": "real_test_pr", "error": str(exc)},
        ) from exc

    elapsed = time.perf_counter() - started
    GITHUB_REAL_TEST_SUCCESS_TOTAL.labels(repo=repo_value, result="completed").inc()
    GITHUB_REAL_TEST_DURATION_SECONDS.labels(repo=repo_value, result="completed").observe(elapsed)
    REAL_GITHUB_SANDBOX_PRS_TOTAL.labels(result="created").inc()

    pr_url = result["pull_request"].get("url", "")
    issue_url = result["issue"].get("url", "")
    checks_status = ""
    if isinstance(result["checks"], dict):
        runs = result["checks"].get("checks") or []
        if isinstance(runs, list) and runs:
            checks_status = runs[0].get("status", "") or ""

    event_type = "github.real_test_pr.created"
    message = (
        f"github-automation real-test-pr completed (repo={repo_value}, "
        f"branch={req.branch_name}, pr={pr_url})"
    )
    await _publish_real_test_notification(
        req.task_id,
        event_type,
        message,
        pr_url=pr_url,
        repo=repo_value,
        branch=req.branch_name,
        sandbox=True,
    )
    # Stage 32 mirror event so the operations view + verify script can
    # filter on the sandbox-PR-created marker without parsing
    # github.real_test_pr.created.
    await _publish_real_test_notification(
        req.task_id,
        "github.sandbox_pr.created",
        message,
        pr_url=pr_url,
        repo=repo_value,
        branch=req.branch_name,
        sandbox=True,
    )
    await _record_real_test_audit(
        task_id=req.task_id,
        workflow_id=req.workflow_id,
        decision_type="github_real_test",
        summary=(f"real GitHub test completed (repo={repo_value}, " f"branch={req.branch_name})"),
        result="ok",
        artifact_refs={
            "issue_url": issue_url,
            "branch": req.branch_name,
            "pr_url": pr_url,
            "checks_status": checks_status,
            "repo": repo_value,
            "test_mode": True,
            "dry_run": False,
            "real_github_test": True,
            "production_executed": False,
        },
    )
    await _record_real_test_audit(
        task_id=req.task_id,
        workflow_id=req.workflow_id,
        decision_type="github_sandbox_pr_created",
        summary=(
            f"sandbox PR created (repo={repo_value}, branch={req.branch_name}, " f"pr={pr_url})"
        ),
        result="ok",
        artifact_refs={
            "repo": repo_value,
            "branch": req.branch_name,
            "pr_url": pr_url,
            "issue_url": issue_url,
            "test_mode": True,
            "dry_run": False,
            "production_executed": False,
        },
    )
    result["event_type"] = event_type
    result["checks_status"] = checks_status
    return result
