"""Step 51.2B -- external egress disabled for all integrations."""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CHART = ROOT / "infra" / "kubernetes" / "charts" / "ai-agents-platform"
CATALOG = ROOT / "infra" / "kubernetes" / "network-connectivity-catalog.yaml"


def _values() -> dict:
    return yaml.safe_load((CHART / "values.yaml").read_text(encoding="utf-8"))


def test_external_egress_flag_disabled() -> None:
    assert _values()["networkPolicy"]["externalEgress"]["enabled"] is False


def test_external_dependencies_all_disabled() -> None:
    cat = yaml.safe_load(CATALOG.read_text(encoding="utf-8"))
    types = {d["dependencyType"] for d in cat["externalDependencies"]}
    # the integrations that must never have egress at this baseline
    for t in (
        "github_api",
        "llm_provider",
        "discord",
        "slack",
        "telegram",
        "cloud_api",
        "external_oidc",
    ):
        assert t in types, f"{t} not catalogued"
    for d in cat["externalDependencies"]:
        assert d["enabled"] is False and d["policyGenerated"] is False, d


def test_template_does_not_render_external_egress() -> None:
    tpl = (CHART / "templates" / "networkpolicies.yaml").read_text(encoding="utf-8")
    # no IPBlock / external CIDR egress is generated by the template
    assert "ipBlock" not in tpl
    assert "0.0.0.0/0" not in tpl
    assert "::/0" not in tpl
