"""Step 59 -- sandbox draft PR metadata builder + validation."""

from __future__ import annotations

import pytest

from shared.sdk.sandbox_github import pr_metadata as m

REQUIRED = [
    "Project",
    "Work item",
    "Dispatch",
    "Correlation ID",
    "Summary",
    "Safety scope",
    "Non-production caveat",
    "No production approval",
    "No merge authorization",
    "Generated by AI Agents sandbox flow",
]


def _body() -> str:
    return m.build_body(
        project_key="DEMO",
        project_id="pid",
        work_item_key="WI-0001",
        work_item_title="Add a thing",
        work_item_id="wid",
        dispatch_id=None,
        correlation_id="corr123",
        summary="A sandbox change.",
    )


def test_title_uses_pattern() -> None:
    assert m.build_title("DEMO", "Add a thing").startswith("[Sandbox][Draft] DEMO:")


def test_body_contains_all_required_sections() -> None:
    body = _body().lower()
    for section in REQUIRED:
        assert section.lower() in body


def test_validate_body_rejects_forbidden_content() -> None:
    with pytest.raises(m.PrMetadataError):
        m.validate_body(_body() + "\n\nThis embeds a secret value")
    with pytest.raises(m.PrMetadataError):
        m.validate_body(_body() + "\n\ncredential: xyz")
