"""SecretProvider — env / Vault KV v2 / file-backed mock-vault.

Stage 24 shipped the env-backed default plus a Vault placeholder. Stage
26 adds two real providers behind the same interface:

* :class:`VaultKvSecretProvider` reads Vault KV v2 over HTTP using
  ``VAULT_ADDR`` and ``VAULT_TOKEN``. The token is held in a
  :class:`SecretRef` so a stray ``repr`` / ``str`` / audit row renders
  ``***REDACTED***`` instead of the literal Vault token.
* :class:`MockVaultSecretProvider` reads a local JSON file (intended
  for staging validation). The file is generated by
  ``scripts/bootstrap_mock_vault_secrets.sh`` and gitignored.

A factory :func:`provider_from_env` picks the right concrete class
based on ``SECRET_PROVIDER`` so callers can stay unaware of which
backend is in play. All providers expose:

* :meth:`get_secret` / :meth:`has_secret` (from
  :class:`SecretProvider`)
* :meth:`list_available_secrets` — returns secret NAMES only, never
  values.
* :attr:`status` — a snapshot dict describing the provider's posture
  (``provider``, ``configured``, ``reachable``, ``mock_file_present``,
  …). Safe to embed in ``/operations/safety`` output.

The redaction guarantees from Stage 24 (``SecretRef`` never serialises
its raw value; ``redact_mapping`` rewrites every secret-shaped key) are
unchanged.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any, Iterable, Mapping

from shared.sdk.secrets.models import REDACTION_TOKEN, SecretRef

# Substring match (case-insensitive) on env-var / dict key names. Any
# key that contains one of these is treated as secret-shaped — the
# value is redacted by ``redact_mapping``.
_SECRET_KEY_HINTS: tuple[str, ...] = (
    "token",
    "secret",
    "password",
    "passwd",
    "api_key",
    "apikey",
    "credential",
    "private_key",
)

_PLACEHOLDER_MARKER = "PLACEHOLDER_DO_NOT_COMMIT_REAL_VALUE"

# Provider names recognised by the factory. Kept as a module-level tuple
# so tests + the validator can import the canonical list.
SUPPORTED_PROVIDERS: tuple[str, ...] = ("env", "vault", "mock-vault")


def _is_secret_key(key: str) -> bool:
    key_lower = (key or "").lower()
    return any(hint in key_lower for hint in _SECRET_KEY_HINTS)


def redact(value: Any) -> str:
    """Render any value as ``***REDACTED***``.

    The helper is intentionally lossy — callers should never log a
    secret. The function returns the redaction token unconditionally
    so it's safe to drop into log lines / audit rows / response bodies.
    """
    if value is None or value == "":
        return ""
    return REDACTION_TOKEN


def redact_mapping(mapping: Mapping[str, Any], *, extra_keys: Iterable[str] = ()) -> dict[str, Any]:
    """Return a new dict with every secret-shaped key redacted.

    ``extra_keys`` allows the caller to opt-in additional names that
    don't match the default substring heuristic (e.g. project-specific
    aliases).
    """
    extras = {k.lower() for k in extra_keys}
    out: dict[str, Any] = {}
    for key, value in mapping.items():
        key_l = (key or "").lower()
        if _is_secret_key(key) or key_l in extras:
            out[key] = REDACTION_TOKEN if value else value
        else:
            out[key] = value
    return out


class SecretProvider:
    """Abstract base. Concrete providers must implement :meth:`_lookup`."""

    name = "abstract"

    def get_secret(self, name: str) -> SecretRef:
        raw = self._lookup(name)
        if raw is None:
            return SecretRef(name=name, present=False)
        stripped = raw.strip()
        if not stripped or stripped == _PLACEHOLDER_MARKER:
            # Placeholders never count as "present". The validator
            # treats placeholder values as a Stage 24 failure for
            # staging / production-check modes.
            return SecretRef(name=name, present=False)
        return SecretRef(name=name, _value=stripped, present=True)

    def has_secret(self, name: str) -> bool:
        return self.get_secret(name).present

    def list_available_secrets(self) -> list[str]:
        """Return secret NAMES the provider knows about. NEVER values."""
        return []

    @property
    def status(self) -> dict[str, Any]:
        """Provider posture snapshot. Must not contain values."""
        return {"provider": self.name, "configured": True, "reachable": True}

    def _lookup(self, name: str) -> str | None:
        raise NotImplementedError


class EnvSecretProvider(SecretProvider):
    """Read secrets from a snapshot of ``os.environ`` (or a passed dict).

    Tests use the ``env`` kwarg to inject a fixed dict. Production code
    passes nothing and reads the live process environment at call time.
    """

    name = "env"

    def __init__(self, env: Mapping[str, str] | None = None) -> None:
        self._env = env if env is not None else os.environ

    def _lookup(self, name: str) -> str | None:
        try:
            return self._env.get(name)
        except Exception:
            return None

    def list_available_secrets(self) -> list[str]:
        # Env-backed provider is opaque — the SDK doesn't enumerate the
        # OS environment because that risks surfacing unrelated keys.
        # Return an empty list; callers should query specific names.
        return []

    @property
    def status(self) -> dict[str, Any]:
        return {"provider": self.name, "configured": True, "reachable": True}


class VaultPlaceholderProvider(SecretProvider):
    """Stage 24 placeholder. Kept for backwards compatibility.

    Real Vault KV v2 lives in :class:`VaultKvSecretProvider`. Code that
    imports the placeholder still works — every lookup returns ``None``
    so a missed migration is loud, not silent.
    """

    name = "vault-placeholder"

    def __init__(self, vault_addr: str | None = None) -> None:
        self.vault_addr = vault_addr or os.environ.get("VAULT_ADDR", "")

    def _lookup(self, name: str) -> str | None:  # noqa: ARG002
        return None


class VaultKvSecretProvider(SecretProvider):
    """Vault KV v2 reader using the bare HTTP API.

    The provider is intentionally minimal — it makes ONE GET call per
    lookup against ``${VAULT_ADDR}/v1/${mount}/data/${path}`` and pulls
    the requested key out of ``data.data``. No write paths exist on
    the SDK; rotation is performed by the operator via Vault directly.

    Failures (missing addr, missing token, HTTP error, JSON parse
    error) are SAFE: the provider logs nothing, returns ``None``, and
    the SecretRef stays ``present=False`` so the consumer falls back
    to its safe-degraded path.
    """

    name = "vault"

    DEFAULT_MOUNT = "secret"
    DEFAULT_PATH = "aiagents/staging"

    def __init__(
        self,
        *,
        addr: str | None = None,
        token_ref: SecretRef | None = None,
        mount: str | None = None,
        path: str | None = None,
        timeout: float = 3.0,
        # Tests inject a callable that mimics httpx.get; production code
        # leaves this None and httpx is imported lazily.
        http_getter: Any = None,
    ) -> None:
        self.addr = (addr or os.environ.get("VAULT_ADDR") or "").rstrip("/")
        if token_ref is None:
            raw = os.environ.get("VAULT_TOKEN") or ""
            self._token_ref = SecretRef(
                name="VAULT_TOKEN",
                _value=raw,
                present=bool(raw and raw != _PLACEHOLDER_MARKER),
            )
        else:
            self._token_ref = token_ref
        self.mount = mount or os.environ.get("VAULT_KV_MOUNT") or self.DEFAULT_MOUNT
        self.path = path or os.environ.get("VAULT_KV_PATH") or self.DEFAULT_PATH
        self.timeout = timeout
        self._http_getter = http_getter
        self._cache: dict[str, str] | None = None
        self._last_error: str = ""

    # ---- helpers --------------------------------------------------------

    def _do_get(self, url: str, headers: dict[str, str]) -> tuple[int, dict[str, Any], str]:
        if self._http_getter is not None:
            try:
                code, body = self._http_getter(url, headers, self.timeout)
                return int(code), body if isinstance(body, dict) else {}, ""
            except Exception as exc:  # pragma: no cover — test stub
                return 0, {}, f"{exc.__class__.__name__}: {exc}"
        try:
            import httpx  # type: ignore
        except ImportError:  # pragma: no cover
            return 0, {}, "httpx_unavailable"
        try:
            response = httpx.get(url, headers=headers, timeout=self.timeout)
            try:
                body = response.json()
            except Exception:
                body = {}
            return response.status_code, body if isinstance(body, dict) else {}, ""
        except Exception as exc:
            return 0, {}, f"{exc.__class__.__name__}: {exc}"

    def _load_kv(self) -> dict[str, str]:
        if self._cache is not None:
            return self._cache
        if not self.addr or not self._token_ref.present:
            self._cache = {}
            self._last_error = "vault_not_configured"
            return self._cache
        url = f"{self.addr}/v1/{self.mount}/data/{self.path}"
        headers = {"X-Vault-Token": self._token_ref.reveal()}
        status, body, err = self._do_get(url, headers)
        if status != 200 or not isinstance(body, dict):
            self._last_error = err or f"http_{status}"
            self._cache = {}
            return self._cache
        data_outer = body.get("data") if isinstance(body, dict) else {}
        data_inner = data_outer.get("data") if isinstance(data_outer, dict) else {}
        if not isinstance(data_inner, dict):
            self._last_error = "no_data_section"
            self._cache = {}
            return self._cache
        # Coerce values to strings — Vault returns them as JSON values.
        self._cache = {str(k): "" if v is None else str(v) for k, v in data_inner.items()}
        self._last_error = ""
        return self._cache

    def reload(self) -> None:
        """Force the next ``get_secret`` call to re-fetch Vault."""
        self._cache = None

    # ---- SecretProvider interface ---------------------------------------

    def _lookup(self, name: str) -> str | None:
        try:
            kv = self._load_kv()
        except Exception:
            return None
        return kv.get(name)

    def list_available_secrets(self) -> list[str]:
        try:
            return sorted(self._load_kv().keys())
        except Exception:
            return []

    @property
    def status(self) -> dict[str, Any]:
        configured = bool(self.addr) and self._token_ref.present
        reachable = False
        if configured:
            # Don't refetch here — return the cached posture so /operations
            # /safety stays cheap.
            reachable = self._cache is not None and not self._last_error
        return {
            "provider": self.name,
            "configured": configured,
            "reachable": reachable,
            "addr_present": bool(self.addr),
            "token_present": self._token_ref.present,
            "mount": self.mount,
            "path": self.path,
            "last_error": self._last_error,
            "secret_count": len(self._cache or {}),
        }


class MockVaultSecretProvider(SecretProvider):
    """File-backed mock vault for staging validation.

    The file is a flat JSON object ``{name: value, ...}``. Stored at
    ``infra/runtime/.mock-vault-secrets.local.json`` by default; the
    path is configurable via ``MOCK_VAULT_SECRETS_FILE``.

    Values are read on demand. A change to the file is picked up on
    the next ``reload()`` call — the rotation smoke uses this to assert
    the provider returns the freshly-written secret.

    The provider REFUSES to return a value that matches a known
    real-token prefix (``ghp_``, ``github_pat_``, ``xoxb-``, ``Bot ``,
    ``Bearer ``, ``sk-``) unless the explicit
    ``MOCK_VAULT_ALLOW_REAL_TOKEN_SHAPES=true`` opt-in is set. This
    guard exists so an operator can't accidentally smuggle a real
    token into the mock file and have it ride staging.
    """

    name = "mock-vault"

    DEFAULT_PATH = "infra/runtime/.mock-vault-secrets.local.json"

    _REAL_TOKEN_PATTERNS = (
        re.compile(r"^ghp_[A-Za-z0-9_]{16,}$"),
        re.compile(r"^github_pat_[A-Za-z0-9_]{16,}$"),
        re.compile(r"^xoxb-[A-Za-z0-9-]{8,}$"),
        re.compile(r"^Bot [A-Za-z0-9._-]{20,}$"),
        re.compile(r"^Bearer [A-Za-z0-9._-]{20,}$"),
        re.compile(r"^sk-[A-Za-z0-9]{20,}$"),
    )

    def __init__(
        self,
        *,
        path: str | Path | None = None,
        allow_real_token_shapes: bool | None = None,
    ) -> None:
        self.path = Path(path or os.environ.get("MOCK_VAULT_SECRETS_FILE") or self.DEFAULT_PATH)
        if allow_real_token_shapes is None:
            allow_real_token_shapes = (
                os.environ.get("MOCK_VAULT_ALLOW_REAL_TOKEN_SHAPES") or ""
            ).strip().lower() == "true"
        self._allow_real_token_shapes = allow_real_token_shapes
        self._cache: dict[str, str] | None = None
        self._last_error: str = ""

    def _load(self) -> dict[str, str]:
        if self._cache is not None:
            return self._cache
        if not self.path.is_file():
            self._cache = {}
            self._last_error = "mock_file_missing"
            return self._cache
        try:
            raw = json.loads(self.path.read_text(encoding="utf-8"))
        except Exception as exc:
            self._cache = {}
            self._last_error = f"parse_error: {exc.__class__.__name__}"
            return self._cache
        if not isinstance(raw, dict):
            self._cache = {}
            self._last_error = "not_a_mapping"
            return self._cache
        self._cache = {str(k): "" if v is None else str(v) for k, v in raw.items()}
        self._last_error = ""
        return self._cache

    def _looks_like_real_token(self, value: str) -> bool:
        for pat in self._REAL_TOKEN_PATTERNS:
            if pat.match(value):
                return True
        return False

    def reload(self) -> None:
        """Force the next ``get_secret`` call to re-read the file."""
        self._cache = None

    # ---- SecretProvider interface ---------------------------------------

    def _lookup(self, name: str) -> str | None:
        try:
            kv = self._load()
        except Exception:
            return None
        value = kv.get(name)
        if value is None:
            return None
        if value and not self._allow_real_token_shapes and self._looks_like_real_token(value):
            # Refuse to return the value. Treated as a missing secret so
            # the consumer falls back to its safe-degraded path.
            self._last_error = f"refused_real_token_shape:{name}"
            return None
        return value

    def list_available_secrets(self) -> list[str]:
        try:
            return sorted(self._load().keys())
        except Exception:
            return []

    @property
    def status(self) -> dict[str, Any]:
        # Don't reload here — keep status cheap. _load() updates the
        # error string as it caches.
        present = self.path.is_file()
        return {
            "provider": self.name,
            "configured": present,
            "reachable": present and not self._last_error,
            "mock_file_present": present,
            "mock_file_path": str(self.path),
            "last_error": self._last_error,
            "secret_count": len(self._cache or {}),
            "allow_real_token_shapes": self._allow_real_token_shapes,
        }


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------


_DEFAULT_PROVIDER: SecretProvider | None = None


def provider_from_env(env: Mapping[str, str] | None = None) -> SecretProvider:
    """Construct a SecretProvider based on ``SECRET_PROVIDER``.

    Unknown values fall back to :class:`EnvSecretProvider` — the safe
    default. The factory NEVER raises; callers can trust they will get
    a working (possibly safe-degraded) provider back.
    """
    snapshot = env if env is not None else os.environ
    choice = (snapshot.get("SECRET_PROVIDER") or "env").strip().lower()
    if choice == "vault":
        return VaultKvSecretProvider()
    if choice == "mock-vault":
        return MockVaultSecretProvider()
    return EnvSecretProvider()


def default_provider() -> SecretProvider:
    """Return the singleton SecretProvider for the current process.

    Tests reset the singleton by importing this module and clearing
    ``_DEFAULT_PROVIDER``; production code just calls the function.
    """
    global _DEFAULT_PROVIDER
    if _DEFAULT_PROVIDER is None:
        _DEFAULT_PROVIDER = provider_from_env()
    return _DEFAULT_PROVIDER


def reset_default_provider() -> None:
    """Drop the singleton so the next ``default_provider()`` call rebuilds."""
    global _DEFAULT_PROVIDER
    _DEFAULT_PROVIDER = None


# Detection helper used by the validator + tests to fail loudly when a
# placeholder slips into a "live" env.
_PLACEHOLDER_REGEX = re.compile(re.escape(_PLACEHOLDER_MARKER))


def looks_like_placeholder(value: str | None) -> bool:
    if not value:
        return False
    return bool(_PLACEHOLDER_REGEX.search(value))
