"""Step 59 -- sandbox draft PR title / body builder + validation.

The body always carries the non-production / no-merge / no-production-approval
caveats and never embeds a secret, token, raw prompt, chain-of-thought, production
approval claim, or customer data.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[3]
METADATA_YAML = ROOT / "infra" / "github" / "sandbox-draft-pr-metadata-model.yaml"


class PrMetadataError(ValueError):
    pass


@lru_cache(maxsize=1)
def load_metadata_model() -> dict[str, Any]:
    data = yaml.safe_load(METADATA_YAML.read_text(encoding="utf-8")) or {}
    return data.get("sandboxDraftPrMetadata", {}) or {}


def build_title(project_key: str, work_item_title: str) -> str:
    pattern = str(
        load_metadata_model().get(
            "titlePattern", "[Sandbox][Draft] {project_key}: {work_item_title}"
        )
    )
    return pattern.format(project_key=project_key, work_item_title=work_item_title)


def build_body(
    *,
    project_key: str,
    project_id: str,
    work_item_key: str,
    work_item_title: str,
    work_item_id: str,
    dispatch_id: str | None,
    correlation_id: str,
    summary: str,
) -> str:
    model = load_metadata_model()
    caveats = model.get("caveats", {}) or {}
    lines = [
        f"## Project\n{project_key} ({project_id})",
        f"## Work item\n{work_item_key}: {work_item_title} ({work_item_id})",
        f"## Dispatch\n{dispatch_id or 'n/a'}",
        f"## Correlation ID\n{correlation_id}",
        f"## Summary\n{summary}",
        "## Safety scope\nSandbox-only draft PR. No merge, no ready-for-review, no production action.",
        f"## Non-production caveat\n{caveats.get('nonProduction', 'Non-production sandbox draft.')}",
        f"## No production approval\n{caveats.get('noProductionApproval', 'No production approval.')}",
        f"## No merge authorization\n{caveats.get('noMerge', 'No merge authorization.')}",
        f"## Generated by AI Agents sandbox flow\n{caveats.get('generatedBy', 'Generated by AI Agents sandbox flow.')}",
    ]
    body = "\n\n".join(lines)
    validate_body(body)
    return body


def validate_body(body: str) -> None:
    model = load_metadata_model()
    low = body.lower()
    for section in model.get("bodyRequiredSections", []) or []:
        if section.lower() not in low:
            raise PrMetadataError(f"body missing required section: {section}")
    for forbidden in model.get("bodyForbiddenContent", []) or []:
        if forbidden.lower() in low:
            raise PrMetadataError(f"body contains forbidden content: {forbidden}")
