"""Stage 46 -- agent discussion audit decision_type constants."""

from __future__ import annotations

DECISION_AGENT_DISCUSSION_STARTED = "agent_discussion_started"
DECISION_AGENT_DISCUSSION_COMPLETED = "agent_discussion_completed"
DECISION_AGENT_DISCUSSION_CONTRIBUTION_RECORDED = "agent_discussion_contribution_recorded"

AGENT_DISCUSSION_DECISION_TYPES: tuple[str, ...] = (
    DECISION_AGENT_DISCUSSION_STARTED,
    DECISION_AGENT_DISCUSSION_COMPLETED,
    DECISION_AGENT_DISCUSSION_CONTRIBUTION_RECORDED,
)

__all__ = [
    "DECISION_AGENT_DISCUSSION_STARTED",
    "DECISION_AGENT_DISCUSSION_COMPLETED",
    "DECISION_AGENT_DISCUSSION_CONTRIBUTION_RECORDED",
    "AGENT_DISCUSSION_DECISION_TYPES",
]
