"""Stage 41 -- verification environment hygiene SDK.

Public surface:
* Audit decision_type constants for verification events.
* Notification event names (all in DEFAULT_REAL_DELIVERY_DENYLIST).
* :func:`classify_regression_result` -- classify a single script result.
* :func:`is_allowed_result` -- whether a result class is an allowed outcome.
"""

from shared.sdk.verification.audit_events import (
    DECISION_FULL_REGRESSION_FAILED,
    DECISION_FULL_REGRESSION_PASS_WITH_GAPS,
    DECISION_FULL_REGRESSION_PASSED,
    DECISION_FULL_REGRESSION_STARTED,
    DECISION_HOST_DEPENDENCY_CAVEAT_CLOSED,
    DECISION_VERIFICATION_DEPENDENCY_MISSING,
    DECISION_VERIFICATION_DEPENDENCY_READY,
    DECISION_VERIFICATION_ENVIRONMENT_CHECKED,
    EVENT_FULL_REGRESSION_FAILED,
    EVENT_FULL_REGRESSION_PASS_WITH_GAPS,
    EVENT_FULL_REGRESSION_PASSED,
    EVENT_VERIFICATION_ENVIRONMENT_FAILED,
    EVENT_VERIFICATION_ENVIRONMENT_READY,
)
from shared.sdk.verification.classifier import classify_regression_result, is_allowed_result

__all__ = [
    "DECISION_VERIFICATION_ENVIRONMENT_CHECKED",
    "DECISION_VERIFICATION_DEPENDENCY_MISSING",
    "DECISION_VERIFICATION_DEPENDENCY_READY",
    "DECISION_FULL_REGRESSION_STARTED",
    "DECISION_FULL_REGRESSION_PASSED",
    "DECISION_FULL_REGRESSION_FAILED",
    "DECISION_FULL_REGRESSION_PASS_WITH_GAPS",
    "DECISION_HOST_DEPENDENCY_CAVEAT_CLOSED",
    "EVENT_VERIFICATION_ENVIRONMENT_READY",
    "EVENT_VERIFICATION_ENVIRONMENT_FAILED",
    "EVENT_FULL_REGRESSION_PASSED",
    "EVENT_FULL_REGRESSION_FAILED",
    "EVENT_FULL_REGRESSION_PASS_WITH_GAPS",
    "classify_regression_result",
    "is_allowed_result",
]
