#!/usr/bin/env bash
# Stage 25 staging env generator.
#
# Produces ``infra/runtime/.env.staging.local`` from
# ``infra/runtime/env.staging.example`` with a freshly generated random
# value for ``POSTGRES_PASSWORD``. Other secret-shaped fields keep their
# placeholder marker so the validator can flag any forgotten edit.
#
# The generated file is gitignored. The script refuses to overwrite an
# existing file unless ``ALLOW_OVERWRITE=true`` is set so an operator
# can't accidentally regenerate a password the running staging stack
# is using.
#
# Run from the repository root.
set -uo pipefail

EXAMPLE="${EXAMPLE:-infra/runtime/env.staging.example}"
OUT="${OUT:-infra/runtime/.env.staging.local}"

echo "### generate_staging_env start: $(date '+%Y-%m-%d %H:%M:%S %Z')"

if [ ! -f "$EXAMPLE" ]; then
  echo "GENERATE_STAGING_ENV: FAIL (template missing: $EXAMPLE)"
  exit 1
fi

if [ -f "$OUT" ] && [ "${ALLOW_OVERWRITE:-false}" != "true" ]; then
  echo "GENERATE_STAGING_ENV: SKIP ($OUT already exists; set ALLOW_OVERWRITE=true to regenerate)"
  echo "  reusing existing $OUT"
  exit 0
fi

# Random base64 password, 32 bytes of entropy. ``openssl`` is in every
# Postgres-capable image and standard on every Linux distro we deploy
# on; fall back to /dev/urandom if it's missing.
gen_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '\n=/+' | head -c 32
  else
    head -c 256 /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 32
  fi
}

pw=$(gen_password)
if [ -z "$pw" ] || [ ${#pw} -lt 16 ]; then
  echo "GENERATE_STAGING_ENV: FAIL (unable to produce a random password)"
  exit 1
fi

# Read template, swap POSTGRES_PASSWORD's placeholder with the generated
# value. We DO NOT substitute the GitHub / Discord / Vault tokens — they
# stay as the placeholder marker so the operator either fills them in
# deliberately or leaves the platform in sandbox-by-default mode.
#
# Sed is intentionally line-oriented: ``s|...|...|`` with a `|` delimiter
# avoids escaping problems with `=` and `/` in the substituted value.
{
  echo "# Generated by scripts/generate_staging_env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "# This file is gitignored. Do NOT commit it."
  echo "# Regenerate with: ALLOW_OVERWRITE=true ./scripts/generate_staging_env.sh"
  echo
  sed "s|^POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${pw}|" "$EXAMPLE"
} > "$OUT"

# Restrict permissions — the password is real (in the sense that the
# staging stack uses it) so the file should not be world-readable.
chmod 600 "$OUT" 2>/dev/null || true

echo "  wrote $OUT (chmod 600, ${#pw} chars password)"

# The validator can be pointed at the generated file via --env-file.
echo "  to validate: ./scripts/validate_runtime_config.sh --mode staging --env-file $OUT"
echo "GENERATE_STAGING_ENV: PASS"
