#!/usr/bin/env python3
"""Step 59 -- sandbox draft PR metadata verifier (SDK).

Marker: SANDBOX_GITHUB_PR_METADATA_VERIFY: PASS | FAIL
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
MARKER = "SANDBOX_GITHUB_PR_METADATA_VERIFY"

failures: list[str] = []


def bad(m: str) -> None:
    failures.append(m)
    print(f"  [FAIL] {m}")


def main() -> int:
    from shared.sdk.sandbox_github import pr_metadata as m

    title = m.build_title("DEMO", "Add a thing")
    if not title.startswith("[Sandbox][Draft]"):
        bad(f"title must use the [Sandbox][Draft] pattern: {title}")

    body = m.build_body(
        project_key="DEMO",
        project_id="pid",
        work_item_key="WI-0001",
        work_item_title="Add a thing",
        work_item_id="wid",
        dispatch_id=None,
        correlation_id="corr123",
        summary="A sandbox change.",
    )
    for section in (
        "Project",
        "Work item",
        "Dispatch",
        "Correlation ID",
        "Summary",
        "Safety scope",
        "Non-production caveat",
        "No production approval",
        "No merge authorization",
        "Generated by AI Agents sandbox flow",
    ):
        if section.lower() not in body.lower():
            bad(f"body missing required section: {section}")

    # Forbidden content must be rejected by validate_body. (Use the forbidden word only --
    # never embed a real token-shaped literal, which the repo secret-leak scanner flags.)
    try:
        m.validate_body(body + "\n\ntoken: <redacted-in-test>")
        bad("validate_body must reject a body that mentions a token")
    except m.PrMetadataError:
        pass

    if failures:
        print(f"{MARKER}: FAIL")
        return 1
    print("  [OK] PR metadata: title pattern, all caveats present, forbidden content rejected")
    print(f"{MARKER}: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
